spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

  data:
    mongodb:
      database: gateway
      host: localhost
      port: 27017

queue:
  gateway: requests-queue
exchange:
  gateway: requests-exchange
routing_key:
  gateway: "*"
